name: A simple test Workflow

on: 
  pull_request: pull_request


jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        users: actions/setup-node@v2
        with:
          node-version: 22.x
    
      - name: run install, build and test
        run: |
          pnpm install
          pnpm run build
          pnpm run test